# --------------------------------------------------
# Labeler configuration file.
#
# Automatically applies labels to pull requests based on branch names and
# changed files. Labels align with the Conventional Commits specification and
# the organization label set.
#
# For more information please see:
# https://github.com/actions/labeler
# --------------------------------------------------

# yaml-language-server: $schema=https://www.schemastore.org/pull-request-labeler.json

feat:
  - any:
      - head-branch: [^feat/, ^feature/]

fix:
  - any:
      - head-branch: [^fix/, ^bugfix/, ^hotfix/]

breaking-change:
  - any:
      - head-branch: [^breaking/, ^breaking-change/]

refactor:
  - any:
      - head-branch: [^refactor/]

perf:
  - any:
      - head-branch: [^perf/]

revert:
  - any:
      - head-branch: [^revert/]

chore:
  - any:
      - head-branch: [^chore/]

docs:
  - any:
      - head-branch: [^docs/]
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.md"
              - "**/docs/**"

ci:
  - any:
      - head-branch: [^ci/]
      - changed-files:
          - any-glob-to-any-file:
              - "**/.devcontainer/**"
              - "**/.github/actions/**"
              - "**/.github/workflows/**"
              - "**/.github/dependabot.yml"
              - "**/.github/labeler.yml"
              - "**/.github/zizmor.yml"
              - "**/.husky/**"
              - "**/scripts/**"
              - "**/.nlobby4.yml"
              - "**/.npmrc"
              - "**/.tool-versions"
              - "**/knip.json"

# TODO: Add your build systems
build:
  - any:
      - head-branch: [^build/]

# TODO: Add further linter or formatter configuration files
style:
  - any:
      - head-branch: [^style/]
      - changed-files:
          - any-glob-to-any-file:
              - "**/.editorconfig"
              - "**/prettier.config.*"
              - "**/commitlint.config.*"
              - "**/.cspell.json"
              - "**/.markdownlint.json"
              - "**/.shellcheckrc"

# TODO: Adjust to fit your testing framework
test:
  - any:
      - head-branch: [^test/]

# TODO: Adjust if using other package ecosystems
dependencies:
  - any:
      - head-branch: [^dependabot/]
      - changed-files:
          - any-glob-to-any-file:
              - "**/package-lock.json"
              - "**/package.json"
