# --------------------------------------------------
# Zizmor configuration file.
#
# Zizmor audits GitHub Actions workflows and action definitions for
# security issues.
#
# For more information please see:
# https://docs.zizmor.sh/configuration/
# --------------------------------------------------

# yaml-language-server: $schema=https://raw.githubusercontent.com/woodruffw/zizmor/main/support/zizmor.schema.json

rules:
  unpinned-uses:
    config:
      policies:
        "*": hash-pin
