# --------------------------------------------------
# Zizmor configuration file.
#
# Zizmor audits GitHub Actions workflows and action definitions for
# security issues.
#
# For more information please see:
# https://docs.zizmor.sh/configuration/
# --------------------------------------------------

rules:
  dangerous-triggers:
    ignore:
      # pull_request_target is intentional in PR automation
      # the workflow will never checkout or execute pull request code.
      - pr-automation.yml:21
  unpinned-uses:
    config:
      policies:
        "*": hash-pin
