# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: Request a feature
description: A request, idea, enhancement or new functionality
title: "[FEATURE] <title>"
type: Feature
labels:
  - feat
  - needs-triage
# TODO: Update assignees to the appropriate team members
assignees:
  - exquz3me
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        Provide detailed information for a feature that should be added.

        NOTE: Before submitting, please search for duplicate or closed proposals.
    validations:
      required: true
