# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: Ask a question
description: Ask a question about the project
title: "[QUESTION] <title>"
type: Question
labels:
  - question
# TODO: Update assignees to the appropriate team members
assignees:
  - exquz3me
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: |
        Ask anything related to the project.

        NOTE: Before submitting, please search for duplicate or closed questions.
    validations:
      required: true
