#!/usr/bin/env sh

# --------------------------------------------------
# Commit message hook.
#
# Runs after Git prepares the commit message and before the
# commit is created.
# Failures here block the commit.
#
# To skip this hook in exceptional cases:
# git commit --no-verify
# --------------------------------------------------

# Run commitlint against the commit message file passed by Git
# Use `npm run commit` for an interactive prompt
npx --no -- commitlint --edit "$1" --verbose
